### ISSUE TITLE
server side rendering

### ISSUE THREAD

**Issue by onerzafer** [gokerlek/goker-blog#15]
In general react is perfect but server side rendering is not coming out of the box. So there are libraries or frameworks build on top of react which is perfect for the purpose. One of them is [nextjs](https://nextjs.org/)

There is a good tutorial about[ how to migrate from create-react-app and react-router](https://nextjs.org/docs/migrating/from-create-react-app)

So please investigate the probability or work load

**Comment by gokerlek** [comment]
Am I just trying to figure out what happened?

**Comment by onerzafer** [comment]
This task is about finding out if it is possible and if possible what other steps we need to take?
