### ISSUE TITLE
Create a page container

### ISSUE THREAD

**Issue by onerzafer** [gokerlek/goker-blog#4]
A page container would be awesome to center the content in the middle of the screen. With a maximum 720px width it would be better to read and focus.
Usage suggestion:

`<Container>All the page content</Container>`

**Comment by onerzafer** [comment]
Day1 can be placed inside and also inside the header and footer the contents can be placed inside container

**Comment by gokerlek** [comment]
I'll make a div called wrapper.js. There will be "header", "container" and "footer" in the wrapper. is it okay
